# Generated by Django 3.2.3 on 2021-06-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='url',
        ),
    ]
