# Generated by Django 3.2.3 on 2021-06-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_page', '0002_auto_20210618_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='hunter',
            new_name='publisher',
        ),
    ]
