# Generated by Django 3.2.4 on 2021-06-24 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate_page', '0004_candidate_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(choices=[('Chair', 'Chair'), ('Vice Chair', 'Vice Chair'), ('Secretary General', 'Secretary General'), ('Vice Secretary General', 'Vice Secretary General'), ('Treasurer', 'Treasurer'), ('Public Relations', 'Public Relations'), ('Vice Public Relations', 'Vice Public Relations'), ('Regional Representative', 'Regional Representative')], max_length=23)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='votes_total',
        ),
        migrations.AddField(
            model_name='candidate',
            name='total_vote',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='body',
            field=models.TextField(help_text='Write a brief introduction of yourself', verbose_name=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Profile Picture'),
        ),
        migrations.CreateModel(
            name='Vresults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_page.position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_page.position'),
        ),
    ]
