# Generated by Django 3.2.4 on 2021-06-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_page', '0006_alter_position_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='post',
            field=models.CharField(choices=[('Chair', 'Chair'), ('Vice Chair', 'Vice Chair'), ('Secretary General', 'Secretary General'), ('Vice Secretary General', 'Vice Secretary General'), ('Treasurer', 'Treasurer'), ('Public Relations', 'Public Relations'), ('Vice Public Relations', 'Vice Public Relations'), ('Regional Representative', 'Regional Representative')], max_length=23),
        ),
    ]
