# Generated by Django 3.2.4 on 2021-06-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_page', '0008_alter_position_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='post',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
