# Generated by Django 3.2.4 on 2021-06-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_page', '0010_auto_20210625_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='user',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='vresults',
            old_name='user',
            new_name='account',
        ),
        migrations.AddField(
            model_name='candidate',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
