# Generated by Django 3.2.4 on 2021-06-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_page', '0011_auto_20210625_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='post',
            new_name='position_text',
        ),
    ]
