# Generated by Django 3.2.4 on 2021-06-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_page', '0013_alter_candidate_total_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='position_text',
            new_name='position',
        ),
    ]
